name: omniversify_core
description: The Foundation of the the Omniversify Project, this package started as a way for the Omniversify design language to be shared across its apps, but as we went through the code, we discovered that it could be cleared a bit and used by everyone, so if you like the design pattern, the responsiveness, the seo friendly routing system, the custom widgets, feel free to use it and if there is any suggestion that you think might help the package with a better performance, feel free to submit your PR.I'm just a solo amateur dev for now, so if I took some time to reply or fix something, please don't hold it against me.
version: 0.0.2
homepage: https://omniversify.com
repository: https://github.com/phaylali/omniversify_core

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_strategy: ^0.2.0
  url_launcher: ^6.1.6
  get: ^4.6.5
  get_storage: ^2.0.3
  flutter_svg: ^1.1.5
  intl: ^0.17.0
  google_fonts: ^3.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/